"""Small pyrealsense2-compatible adapter for the methods used by camera_controller.

Gazebo color and depth images are generated by one sensor, so they are already
aligned. This adapter does not imitate the full RealSense SDK.
"""
import os
import threading
import time

import numpy as np
import rclpy
from cv_bridge import CvBridge
from rclpy.node import Node
from rclpy.qos import qos_profile_sensor_data
from sensor_msgs.msg import Image


class stream:
    color = 'color'
    depth = 'depth'


class format:
    bgr8 = 'bgr8'
    z16 = 'z16'


class config:
    def enable_stream(self, *_args):
        pass


class _Frame:
    def __init__(self, data):
        self.data = data

    def get_data(self):
        return self.data

    def get_distance(self, x, y):
        value = float(self.data[y, x])
        if not np.isfinite(value) or value <= 0:
            return 0.0
        return value / 1000.0 if self.data.dtype == np.uint16 else value


class _Frames:
    def __init__(self, color, depth):
        self.color = _Frame(color)
        self.depth = _Frame(depth)

    def get_color_frame(self):
        return self.color

    def get_depth_frame(self):
        return self.depth


class align:
    def __init__(self, _stream):
        pass

    def process(self, frames):
        return frames


class _Receiver(Node):
    def __init__(self):
        super().__init__('sim_realsense_receiver')
        self.bridge = CvBridge()
        self.color = None
        self.depth = None
        self.create_subscription(Image, os.getenv('SIM_COLOR_TOPIC', '/d435/image_raw'),
                                 self.on_color, qos_profile_sensor_data)
        self.create_subscription(Image, os.getenv('SIM_DEPTH_TOPIC', '/d435/depth/image_raw'),
                                 self.on_depth, qos_profile_sensor_data)

    def on_color(self, msg):
        self.color = self.bridge.imgmsg_to_cv2(msg, desired_encoding='bgr8')

    def on_depth(self, msg):
        self.depth = self.bridge.imgmsg_to_cv2(msg, desired_encoding='passthrough')


class pipeline:
    def __init__(self):
        self.receiver = None
        self.thread = None

    def start(self, _config):
        if not rclpy.ok():
            rclpy.init()
        self.receiver = _Receiver()
        self.thread = threading.Thread(target=rclpy.spin, args=(self.receiver,), daemon=True)
        self.thread.start()

    def wait_for_frames(self):
        deadline = time.time() + 10
        while time.time() < deadline:
            if self.receiver.color is not None and self.receiver.depth is not None:
                return _Frames(self.receiver.color.copy(), self.receiver.depth.copy())
            time.sleep(0.03)
        raise TimeoutError('No simulated D435 frames within 10 seconds')

    def stop(self):
        if self.receiver:
            self.receiver.destroy_node()
            self.receiver = None
